project:
  type: website
  output-dir: ../docs/
  resources:
    - quarto/

website:
  title: "Larval seedboxes"
  search: false
  navbar:
    left:
      - file: codebase.qmd
      - icon: github
        href: https://github.com/marine-ecologist/seedbox
        aria-label: GitHub

format:
  html:
    theme: cyborg
    page-layout: full
    toc: false

execute:
  echo: true
  warning: false
